version: '3.6'

services:
  # apache2 is only required if using phpmyadmin.
  www:
    image: httpd:2.4
    ports: 
      - "80:80"
    volumes:
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/www
        target: /usr/local/apache2/htdocs
    restart: always
    links:
      - db
    networks:
      - dbphp

  # mysql database is required for database testing.
  db:
    image: mysql:5.7
    volumes:
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/sql
        target: /var/lib/mysql
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/sqldumps
        target: /usr/databases
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: database-tester
      MYSQL_PASSWORD: password
    networks:
      - dbphp

  # phpmyadmin can be used as a database viewer but is not required.
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - dbphp

  # jenkins can be used for remote/automated testing but is not required.
  jenkins:
    image: jenkins:2.60.3
    user: root
    ports: 
      - "8082:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/jenkins
        target: /var/jenkins_home
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/jenkins/home
        target: /home
      - type: bind
        source: c:/Users/skarim/Downloads/db-api-jenkins/jenkins/docker
        target: /var/run/docker.sock
    restart: always

  # rest api is required for rest api testing.
  rest:
    image: ericgoebelbecker/resttutorial
    ports: 
      - "8080:8080"
    restart: always

networks:
  dbphp:
volumes:
  db_data: